module.exports = {
  content: ["./templates/**/*.{html,js}", "./static/js/**/*.js"],
  safelist: ["hidden"],
  theme: {
    container: {
      center: true,
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      padding: {
        DEFAULT: "2rem",
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
      "max-sm": { max: "639px" },
      "max-md": { max: "767px" },
      "max-lg": { max: "1023px" },
      "max-xl": { max: "1279px" },
      "max-2xl": { max: "1535px" },
    },
    extend: {
      colors: {
        body: "#ffffff",
        bodyText: "#111827",
        primary: "#2563eb",
        primaryHover: "#1d4ed8",
        secondary: "#15803d",
        secondaryHover: "#f9fafb",
        accent: "#b45309",
        danger: "#dc2626",
        dangerHover: "#b91c1c",
        success: {
          light: "#dcfce7",
          soft: "#bbf7d0",
          border: "#22c55e",
          DEFAULT: "#15803d",
          dark: "#166534",
        },
        warning: {
          lightest: "#fefce8",
          light: "#fef9c3",
          soft: "#fef08a",
          border: "#eab308",
          medium: "#ca8a04",
          DEFAULT: "#a16207",
          dark: "#854d0e",
        },
        border: "#9ca3af",
        linkHover: "#1e3a8a",
        nav: "#ffffff",
        form: {
          bg: "#ffffff",
          border: "#9ca3af",
          text: "#111827",
        },
        table: {
          border: "#9ca3af",
          headerBg: "#2563eb",
          headerText: "#ffffff",
          hoverBg: "#f3f4f6",
        },
      },
      spacing: {
        0.5: "0.125rem",
        1: "0.25rem",
        2: "0.5rem",
        4: "1rem",
        6: "1.5rem",
        8: "2rem",
        9.5: "2.375rem",
        30: "7.5rem",
      },
      maxWidth: {
        "drawer-sm": "30rem",
        "drawer-md": "32.5rem",
        "drawer-lg": "45rem",
        "drawer-xl": "53.75rem",
      },
      maxHeight: {
        "screen-90": "90vh",
      },
      fontSize: {
        badge: ["clamp(0.8rem, 0.3vw + 0.7rem, 1rem)", { lineHeight: "1" }],
      },
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
      },
      boxShadow: {
        btn: "0 2px 4px rgba(0, 0, 0, 0.25)",
        "form-focus": "0 0 0 2px rgba(29, 78, 216, 0.4)",
      },
    },
  },
  plugins: [
    require("tailwindcss-fluid-type")({
      settings: {
        fontSizeMin: 0.875,
        fontSizeMax: 1.125,
        ratioMin: 1.15,
        ratioMax: 1.2,
        screenMin: 20,
        screenMax: 96,
        unit: "rem",
        prefix: "",
        extendValues: true,
      },
      values: {
        xs: [-2, 1.6],
        sm: [-1, 1.6],
        base: [0, 1.6],
        lg: [1, 1.6],
        xl: [2, 1.4],
        h1: [3, 1.25],
        h2: [2, 1.25],
        h3: [1, 1.3],
        label: [-1, 1.6],
        body: [0, 1.6],
        caption: [-2, 1.6],
      },
    }),
    require("@tailwindcss/forms"),
  ],
};
