"""Application configuration using environment variables.

This module centralizes all environment variable access using
``django-environ`` and provides typed attributes via a dataclass. It allows
other modules to import settings instead of touching ``os.environ``
or ``environ.Env`` directly.

Required variables:
- ``DJANGO_SECRET_KEY``: Secret key for Django (required in production).

Optional variables with defaults:
- ``DJANGO_DEBUG`` (bool): Enable debug mode. Defaults to ``False``.
- ``DJANGO_ALLOWED_HOSTS`` (csv): Comma separated list of allowed hosts.
- ``DATABASE_URL`` (str): Database connection string. Defaults to SQLite.
- ``DATABASE_SSL_REQUIRE`` (bool): Require SSL for Postgres connections.
- ``DJANGO_SUPERUSER_USERNAME`` (str): Username for autogenerated superuser.
- ``DJANGO_SUPERUSER_EMAIL`` (str): Email for autogenerated superuser.
- ``DJANGO_SUPERUSER_PASSWORD`` (str): Password for autogenerated superuser.
- ``STATIC_VERSION`` (str): Cache-busting static version.
- ``CODESPACE_NAME`` (str): Codespaces identifier added to allowed hosts.
- ``DJANGO_SETTINGS_MODULE`` (str): Root settings module.
- ``GITHUB_TOKEN`` (str): Token for GitHub API utilities.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import environ

# Determine project base directory to load a .env file if present
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / ".env"

env = environ.Env()
if ENV_FILE.exists():
    environ.Env.read_env(ENV_FILE)


@dataclass
class Settings:
    """Dataclass holding application configuration."""

    django_settings_module: str
    django_debug: bool
    django_secret_key: Optional[str]
    django_allowed_hosts: List[str]
    database_url: Optional[str]
    database_ssl_require: bool
    database_conn_max_age: int
    django_superuser_username: str
    django_superuser_email: str
    django_superuser_password: Optional[str]
    static_version: str
    codespace_name: Optional[str]
    github_token: Optional[str]
    redis_url: Optional[str]


def load_settings(**overrides: object) -> Settings:
    """Load settings from environment with optional overrides."""
    values = dict(
        django_settings_module=env(
            "DJANGO_SETTINGS_MODULE", default="inventory_app.settings.dev"
        ),
        django_debug=env.bool("DJANGO_DEBUG", default=False),
        django_secret_key=env("DJANGO_SECRET_KEY", default=None),
        django_allowed_hosts=env.list(
            "DJANGO_ALLOWED_HOSTS",
            default=[
                "localhost",
                "testserver",
                "127.0.0.1",
                "curly-space-sniffle-pjxw7ww6r76frgp-8000.app.github.dev",
            ],
        ),
        database_url=env("DATABASE_URL", default=None),
        database_ssl_require=env.bool("DATABASE_SSL_REQUIRE", default=True),
        database_conn_max_age=env.int("DB_CONN_MAX_AGE", default=600),
        django_superuser_username=env("DJANGO_SUPERUSER_USERNAME", default="admin"),
        django_superuser_email=env(
            "DJANGO_SUPERUSER_EMAIL", default="admin@inventory.app"
        ),
        django_superuser_password=env("DJANGO_SUPERUSER_PASSWORD", default=None),
        static_version=env("STATIC_VERSION", default="dev"),
        codespace_name=env("CODESPACE_NAME", default=None),
        github_token=env("GITHUB_TOKEN", default=None),
        redis_url=env("REDIS_URL", default=None),
    )
    values.update(overrides)
    return Settings(**values)


# Singleton settings instance used across the project
settings = load_settings()
