# Generated by Django 5.2.5 on 2025-08-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indent",
            fields=[
                ("indent_id", models.AutoField(primary_key=True, serialize=False)),
                ("mrn", models.TextField(blank=True, null=True, unique=True)),
                ("requested_by", models.TextField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("date_required", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("date_submitted", models.TextField(blank=True, null=True)),
                ("processed_by_user_id", models.TextField(blank=True, null=True)),
                ("date_processed", models.TextField(blank=True, null=True)),
                ("created_at", models.TextField(blank=True, null=True)),
                ("updated_at", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "indents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IndentItem",
            fields=[
                ("indent_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("requested_qty", models.FloatField(blank=True, null=True)),
                ("issued_qty", models.FloatField(blank=True, null=True)),
                ("item_status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "indent_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("base_unit", models.TextField(blank=True, null=True)),
                ("purchase_unit", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("sub_category", models.TextField(blank=True, null=True)),
                ("permitted_departments", models.TextField(blank=True, null=True)),
                ("reorder_point", models.FloatField(blank=True, null=True)),
                ("current_stock", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("updated_at", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_change", models.FloatField(blank=True, null=True)),
                ("transaction_type", models.TextField(blank=True, null=True)),
                ("user_id", models.TextField(blank=True, null=True)),
                ("related_mrn", models.TextField(blank=True, null=True)),
                ("related_po_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("transaction_date", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock_transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("contact_person", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("updated_at", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "suppliers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("po_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField()),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered"),
                            ("PARTIAL", "Partially Received"),
                            ("COMPLETE", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                ("grn_id", models.AutoField(primary_key=True, serialize=False)),
                ("received_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        db_column="po_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "goods_received_notes",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("po_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_ordered", models.FloatField()),
                ("quantity_received", models.FloatField(default=0)),
                ("unit_price", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        db_column="po_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_items",
            },
        ),
        migrations.CreateModel(
            name="GRNItem",
            fields=[
                ("grn_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_ordered_on_po", models.FloatField()),
                ("quantity_received", models.FloatField()),
                ("unit_price_at_receipt", models.FloatField()),
                ("item_notes", models.TextField(blank=True, null=True)),
                (
                    "grn",
                    models.ForeignKey(
                        db_column="grn_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.goodsreceivednote",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        db_column="po_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "db_table": "grn_items",
            },
        ),
    ]
