# Generated by Django 5.2.5 on 2025-08-26 21:02

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import inventory.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indent",
            fields=[
                ("indent_id", models.AutoField(primary_key=True, serialize=False)),
                ("mrn", models.CharField(max_length=100, unique=True)),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("date_required", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("date_submitted", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "processed_by_user_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_processed", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "indents",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("unit_id", models.IntegerField()),
                (
                    "category_id",
                    models.BigIntegerField(
                        blank=True, db_column="category_id_ref", null=True
                    ),
                ),
                (
                    "reorder_point",
                    inventory.models.fields.CoerceFloatField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_stock",
                    inventory.models.fields.CoerceFloatField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("po_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField()),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered"),
                            ("PARTIAL", "Partially Received"),
                            ("COMPLETE", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "purchase_orders",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "default_yield_qty",
                    inventory.models.fields.CoerceFloatField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "default_yield_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plating_notes", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                ("version", models.IntegerField(blank=True, null=True)),
                ("effective_from", models.DateField(auto_now_add=True)),
                ("effective_to", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recipes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "suppliers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IndentItem",
            fields=[
                ("indent_item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "requested_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "issued_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("item_status", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "indent",
                    models.ForeignKey(
                        blank=True,
                        db_column="indent_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.indent",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_column="item_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "indent_items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                ("grn_id", models.AutoField(primary_key=True, serialize=False)),
                ("received_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        db_column="po_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "goods_received_notes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("po_item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        db_column="po_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="GRNItem",
            fields=[
                ("grn_item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_ordered_on_po",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "unit_price_at_receipt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "item_notes",
                    models.TextField(blank=True, db_column="notes", null=True),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        db_column="grn_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.goodsreceivednote",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        db_column="po_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "db_table": "grn_items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SaleTransaction",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    inventory.models.fields.CoerceFloatField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        db_column="recipe_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "sales_transactions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("related_po_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_column="item_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
                (
                    "related_indent",
                    models.ForeignKey(
                        blank=True,
                        db_column="related_indent_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.indent",
                    ),
                ),
                (
                    "user_int",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id_int",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stock_transactions",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                db_column="supplier_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="recipe_item_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "component_kind",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "component_id",
                    models.IntegerField(blank=True, db_column="item_id", null=True),
                ),
                (
                    "quantity",
                    inventory.models.fields.CoerceFloatField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "loss_pct",
                    inventory.models.fields.CoerceFloatField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_recipe",
                    models.ForeignKey(
                        db_column="recipe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="components",
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "recipe_items",
                "managed": True,
                "unique_together": {
                    ("parent_recipe", "component_kind", "component_id")
                },
            },
        ),
    ]
