# Generated by Django 5.2.5 on 2025-08-18 10:35

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indent",
            fields=[
                ("indent_id", models.AutoField(primary_key=True, serialize=False)),
                ("mrn", models.TextField(blank=True, null=True, unique=True)),
                ("requested_by", models.TextField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("date_required", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("date_submitted", models.DateTimeField(auto_now_add=True, null=True)),
                ("processed_by_user_id", models.TextField(blank=True, null=True)),
                ("date_processed", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "indents",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("base_unit", models.TextField(blank=True, null=True)),
                ("purchase_unit", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("sub_category", models.TextField(blank=True, null=True)),
                ("permitted_departments", models.TextField(blank=True, null=True)),
                (
                    "reorder_point",
                    inventory.models.CoerceFloatField(blank=True, null=True),
                ),
                (
                    "current_stock",
                    inventory.models.CoerceFloatField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("po_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField()),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered"),
                            ("PARTIAL", "Partially Received"),
                            ("COMPLETE", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("type", models.TextField(blank=True, null=True)),
                (
                    "default_yield_qty",
                    inventory.models.CoerceFloatField(blank=True, null=True),
                ),
                ("default_yield_unit", models.TextField(blank=True, null=True)),
                ("plating_notes", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(blank=True, null=True)),
                ("effective_from", models.DateField(auto_now_add=True)),
                ("effective_to", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recipes",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("contact_person", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "suppliers",
            },
        ),
        migrations.CreateModel(
            name="IndentItem",
            fields=[
                ("indent_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("requested_qty", models.FloatField(blank=True, null=True)),
                ("issued_qty", models.FloatField(blank=True, null=True)),
                ("item_status", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "indent",
                    models.ForeignKey(
                        blank=True,
                        db_column="indent_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.indent",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_column="item_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "indent_items",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                ("grn_id", models.AutoField(primary_key=True, serialize=False)),
                ("received_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        db_column="po_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "goods_received_notes",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("po_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_ordered", models.FloatField()),
                ("quantity_received", models.FloatField(default=0)),
                ("unit_price", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        db_column="po_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_items",
            },
        ),
        migrations.CreateModel(
            name="GRNItem",
            fields=[
                ("grn_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_ordered_on_po", models.FloatField()),
                ("quantity_received", models.FloatField()),
                ("unit_price_at_receipt", models.FloatField()),
                (
                    "grn",
                    models.ForeignKey(
                        db_column="grn_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.goodsreceivednote",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        db_column="po_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "db_table": "grn_items",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_change", models.FloatField(blank=True, null=True)),
                ("transaction_type", models.TextField(blank=True, null=True)),
                ("user_id", models.TextField(blank=True, null=True)),
                ("related_mrn", models.TextField(blank=True, null=True)),
                ("related_po_id", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        db_column="item_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "stock_transactions",
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                db_column="supplier_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.supplier",
            ),
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("component_kind", models.TextField(blank=True, null=True)),
                ("component_id", models.IntegerField(blank=True, null=True)),
                ("quantity", inventory.models.CoerceFloatField(blank=True, null=True)),
                ("unit", models.TextField(blank=True, null=True)),
                ("loss_pct", inventory.models.CoerceFloatField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_recipe",
                    models.ForeignKey(
                        db_column="parent_recipe_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="components",
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "recipe_components",
                "unique_together": {
                    ("parent_recipe", "component_kind", "component_id")
                },
            },
        ),
    ]
