# Generated by Django 5.2.5 on 2025-08-18 08:10

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("type", models.TextField(blank=True, null=True)),
                (
                    "default_yield_qty",
                    inventory.models.CoerceFloatField(blank=True, null=True),
                ),
                ("default_yield_unit", models.TextField(blank=True, null=True)),
                ("plating_notes", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(blank=True, null=True)),
                ("effective_from", models.DateField(auto_now_add=True)),
                ("effective_to", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recipes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("component_kind", models.TextField(blank=True, null=True)),
                ("component_id", models.IntegerField(blank=True, null=True)),
                ("quantity", inventory.models.CoerceFloatField(blank=True, null=True)),
                ("unit", models.TextField(blank=True, null=True)),
                ("loss_pct", inventory.models.CoerceFloatField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recipe_components",
                "managed": False,
            },
        ),
    ]
