# Generated by Django 5.2.5 on 2025-08-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about this item", null=True
            ),
        ),
    ]
