# Generated by Django 5.2.5 on 2025-08-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_add_help_text_to_item_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.TextField(db_column="permitted_departments", unique=True),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ItemDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.department",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Department",
                "verbose_name_plural": "Item Departments",
                "db_table": "item_departments",
                "managed": True,
                "unique_together": {("item", "department")},
            },
        ),
        migrations.AddField(
            model_name="item",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="items",
                through="inventory.ItemDepartment",
                to="inventory.department",
            ),
        ),
    ]
