# Generated by Django 5.2.5 on 2025-08-19 11:48

from django.db import migrations

import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_grnitem_unit_price_at_receipt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="current_stock",
            field=inventory.models.CoerceFloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="reorder_point",
            field=inventory.models.CoerceFloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="default_yield_qty",
            field=inventory.models.CoerceFloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="recipecomponent",
            name="loss_pct",
            field=inventory.models.CoerceFloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="recipecomponent",
            name="quantity",
            field=inventory.models.CoerceFloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="saletransaction",
            name="quantity",
            field=inventory.models.CoerceFloatField(blank=True, default=0.0, null=True),
        ),
    ]
