# Generated by Django 5.2.5 on 2025-08-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="base_unit",
            field=models.CharField(
                blank=True,
                help_text="Base unit of measurement (kg, ltr, pc)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True, help_text="Item category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="initial_purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Initial purchase price per unit",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="last_purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Most recent purchase price per unit",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="lead_time_days",
            field=models.IntegerField(
                blank=True, help_text="Standard lead time in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="minimum_order_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum order quantity",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="preferred_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Default supplier for this item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_items",
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_unit",
            field=models.CharField(
                blank=True,
                help_text="Purchase unit (g, ml, each)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sub_category",
            field=models.CharField(
                blank=True, help_text="Item subcategory", max_length=100, null=True
            ),
        ),
    ]
