# Generated by Django 5.2.5 on 2025-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_business_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Credit limit amount",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                help_text="Standard payment terms (e.g., Net 30)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_rating",
            field=models.IntegerField(
                blank=True, help_text="Supplier rating (1-5 stars)", null=True
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(
                blank=True,
                help_text="Tax identification number",
                max_length=50,
                null=True,
            ),
        ),
    ]
