# Generated by Django 5.2.5 on 2025-08-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_enhance_supplier_fields"),
    ]

    operations = [
        # Add id column as primary key to item_departments table
        migrations.RunSQL(
            """
            DO $$ BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'item_departments' AND column_name = 'id'
              ) THEN
                ALTER TABLE item_departments ADD COLUMN id SERIAL PRIMARY KEY;
              END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE item_departments DROP COLUMN IF EXISTS id;",
        ),
    ]
