# Generated by Django 5.2.5 on 2025-08-30 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_add_id_to_item_departments_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="related_po_id",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="related_po",
            field=models.ForeignKey(
                blank=True,
                db_column="related_po_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="indentitem",
            name="indent",
            field=models.ForeignKey(
                blank=True,
                db_column="indent_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.indent",
            ),
        ),
        migrations.AlterField(
            model_name="indentitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                db_column="item_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="item",
            field=models.ForeignKey(
                blank=True,
                db_column="item_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="related_indent",
            field=models.ForeignKey(
                blank=True,
                db_column="related_indent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.indent",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="user_int",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id_int",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
