# Generated by Django 5.2.5 on 2025-08-22 13:54

from decimal import Decimal
from django.db import migrations
from django.db.models import Sum
from django.utils.timezone import now


def migrate_existing_grn(apps, schema_editor):
    PurchaseOrderItem = apps.get_model("inventory", "PurchaseOrderItem")
    GRNItem = apps.get_model("inventory", "GRNItem")
    GoodsReceivedNote = apps.get_model("inventory", "GoodsReceivedNote")

    for poi in PurchaseOrderItem.objects.all():
        existing = (
            GRNItem.objects.filter(po_item_id=poi.pk).aggregate(
                total=Sum("quantity_received")
            )["total"]
            or Decimal("0")
        )
        qty = getattr(poi, "quantity_received", Decimal("0"))
        diff = qty - existing
        if diff > 0:
            grn = GoodsReceivedNote.objects.create(
                purchase_order_id=poi.purchase_order_id,
                supplier_id=poi.purchase_order.supplier_id,
                received_date=now().date(),
                notes="Migrated from PurchaseOrderItem",
            )
            GRNItem.objects.create(
                grn=grn,
                po_item_id=poi.pk,
                quantity_ordered_on_po=poi.quantity_ordered,
                quantity_received=diff,
                unit_price_at_receipt=poi.unit_price,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_rename_notes_to_item_notes"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_grn, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="quantity_received",
        ),
    ]
