# Generated by Django 5.2.5 on 2025-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_purchaseorderitem_quantity_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="base_unit",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchase_unit",
            field=models.CharField(max_length=50),
        ),
    ]
