# Generated by Django 5.2.5 on 2025-08-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_a_category_unit_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="base_unit",
        ),
        migrations.RemoveField(
            model_name="item",
            name="purchase_unit",
        ),
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="sub_category",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="unit_id",
            new_name="unit",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category_id",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                db_column="unit_id",
                to="inventory.unit",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                db_column="category_id_ref",
                blank=True,
                null=True,
                to="inventory.category",
            ),
        ),
    ]
