# Generated by Django 5.2.5 on 2025-08-30 10:07

from django.db import migrations, models


def create_default_units(apps, schema_editor):
    Unit = apps.get_model("inventory", "Unit")
    Unit.objects.bulk_create(
        [
            Unit(
                unit_id=1,
                base_unit="GM",
                purchase_unit="2 KG",
                conversion_factor=2000.0,
            ),
            Unit(
                unit_id=19,
                base_unit="GM",
                purchase_unit="KG",
                conversion_factor=1000.0,
            ),
            Unit(
                unit_id=55,
                base_unit="PC",
                purchase_unit="PC",
                conversion_factor=1.0,
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_stocktransaction_related_po_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("unit_id", models.AutoField(primary_key=True, serialize=False)),
                ("base_unit", models.CharField(max_length=10)),
                ("purchase_unit", models.CharField(max_length=50)),
                ("conversion_factor", models.FloatField()),
            ],
            options={
                "db_table": "units",
                "ordering": ["base_unit", "purchase_unit"],
                "managed": True,
            },
        ),
        migrations.RunPython(create_default_units, migrations.RunPython.noop),
    ]
