# Generated by Django 5.2.5 on 2025-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RECEIVING", "RECEIVING"),
                    ("ADJUSTMENT", "ADJUSTMENT"),
                    ("WASTAGE", "WASTAGE"),
                    ("SALE", "SALE"),
                    ("ISSUE", "ISSUE"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
