# Generated by Django 5.2.5 on 2025-08-31 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_category_unit_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "managed": True,
                "ordering": ["category", "sub_category"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "managed": True,
                "ordering": ["base_unit", "purchase_unit"],
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-category",
                "verbose_name_plural": "Sub-categories",
                "db_table": "sub_categories",
                "ordering": ["category__category", "name"],
            },
        ),
    ]
