# Generated by Django 5.2.5 on 2025-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_category_options_alter_unit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indent",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("APPROVED", "Approved"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SUBMITTED",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indentitem",
            name="item_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending Issue"),
                    ("ISSUED", "Issued"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=50,
                null=True,
            ),
        ),
    ]
