# Generated by Django 5.2.5 on 2025-09-02 09:06

from django.db import migrations, models
from django.db.utils import ProgrammingError


def clean_notes_fields(apps, schema_editor):
    model_fields = [
        ("GoodsReceivedNote", "notes"),
        ("GRNItem", "item_notes"),
        ("Indent", "notes"),
        ("IndentItem", "notes"),
        ("Item", "notes"),
        ("PurchaseOrder", "notes"),
        ("Recipe", "plating_notes"),
        ("RecipeComponent", "notes"),
        ("SaleTransaction", "notes"),
        ("StockTransaction", "notes"),
        ("Supplier", "notes"),
    ]

    try:
        existing_tables = set(
            schema_editor.connection.introspection.table_names()
        )
    except ProgrammingError:
        existing_tables = set()

    for model_name, field_name in model_fields:
        Model = apps.get_model("inventory", model_name)
        table_name = Model._meta.db_table
        if table_name not in existing_tables:
            continue
        Model.objects.filter(
            **{f"{field_name}__in": [True, False, "True", "False"]}
        ).update(**{field_name: ""})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_indent_status_alter_indentitem_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="grnitem",
            name="item_notes",
            field=models.TextField(
                blank=True, db_column="notes", default="", null=True
            ),
        ),
        migrations.AlterField(
            model_name="indent",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="indentitem",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional notes about this item",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="plating_notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="recipecomponent",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="saletransaction",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.RunPython(clean_notes_fields, noop),
    ]
