# Generated by Django 5.2.5 on 2025-09-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_item_indexes"),
        ("inventory", "0012_alter_goodsreceivednote_notes_and_more"),
    ]

    operations = []
