# Generated by Django 5.2.5 on 2025-09-12 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_item_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(fields=["transaction_date"], name="stx_date_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(fields=["transaction_type"], name="stx_type_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["item", "transaction_date"], name="stx_item_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="supplier_name_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["is_active"], name="supplier_active_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["updated_at"], name="supplier_updated_idx"),
        ),
    ]
