# Generated by Django 5.2.5 on 2025-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_item_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
