# Generated by Django 5.2.5 on 2025-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_stocktransaction_stx_date_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="dept_name_idx"),
        ),
        migrations.AddIndex(
            model_name="itemdepartment",
            index=models.Index(fields=["item"], name="itemdept_item_idx"),
        ),
        migrations.AddIndex(
            model_name="itemdepartment",
            index=models.Index(fields=["department"], name="itemdept_dept_idx"),
        ),
    ]
