# Generated by Django 5.2.5 on 2025-08-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_recipe_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="related_mrn",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="related_indent",
            field=models.ForeignKey(
                blank=True,
                db_column="related_indent_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="inventory.indent",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="user_int",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id_int",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category_id",
            field=models.BigIntegerField(
                blank=True, db_column="category_id_ref", null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
