# Generated by Django 5.2.5 on 2025-08-25 12:34

from django.db import migrations


class Migration(migrations.Migration):
    """Create legacy ``indents`` table only if it is missing.

    Operators may already have an ``indents`` table from a previous system.
    Using ``IF NOT EXISTS`` avoids ``ProgrammingError`` during deployment
    while the model itself is now unmanaged so Django will not attempt
    schema changes on this table.
    """

    dependencies = [
        ("inventory", "0016_remove_stocktransaction_related_mrn_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS indents (
                    indent_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    mrn VARCHAR(100) UNIQUE NOT NULL,
                    requested_by VARCHAR(255),
                    department VARCHAR(100),
                    date_required DATE,
                    notes TEXT,
                    status VARCHAR(50),
                    date_submitted DATETIME,
                    processed_by_user_id VARCHAR(50),
                    date_processed DATETIME,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS indents;",
        )
    ]
