# Generated by Django 5.2.5 on 2026-03-24 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_fix_pk_sequences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksnapshot',
            options={'managed': True, 'ordering': ['snapshot_date']},
        ),
        migrations.AlterUniqueTogether(
            name='recipecomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='indent',
            name='processed_by_user_id',
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='delivery_note_number',
            field=models.CharField(blank=True, help_text='Delivery note or invoice number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='item',
            field=models.ForeignKey(blank=True, db_column='direct_item_id', help_text='Direct item reference (for ad-hoc GRNs without a PO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='indent',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Menu selling price (ex. tax)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='target_food_cost_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, help_text='Target food cost percentage for this item type', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, db_column='sub_recipe_id', help_text='Sub-recipe used as an ingredient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='inventory.recipe'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='from_department',
            field=models.ForeignKey(blank=True, help_text='Source department (for TRANSFER type only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='inventory.department'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='to_department',
            field=models.ForeignKey(blank=True, help_text='Destination department (for TRANSFER type only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='po_item',
            field=models.ForeignKey(blank=True, db_column='po_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='quantity_ordered_on_po',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for a full stock-take across all departments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
            ],
            options={
                'db_table': 'stock_takes',
                'ordering': ['-date', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, help_text='Auto-populated from current stock at time of stock-take creation', max_digits=10)),
                ('physical_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Actual counted quantity entered by staff', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake')),
            ],
            options={
                'db_table': 'stock_take_items',
                'ordering': ['item__name'],
                'managed': True,
            },
        ),
    ]
