# Generated by Django 5.2.5 on 2026-03-19 10:58
#
# NOTE: The live Supabase DB schema drifted ahead of Django's migration state,
# so every structural operation uses SeparateDatabaseAndState with defensive
# SQL (IF EXISTS / IF NOT EXISTS) to guarantee idempotent, crash-free runs
# regardless of the actual DB column/constraint state.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_fix_pk_sequences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. StockSnapshot Meta ─────────────────────────────────────
        # Pure state change – no DDL emitted by Django for AlterModelOptions.
        migrations.AlterModelOptions(
            name="stocksnapshot",
            options={"managed": True, "ordering": ["snapshot_date"]},
        ),
        # ── 2. RecipeComponent unique_together ────────────────────────
        # Constraint never existed in live DB → state-only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="recipecomponent",
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        # ── 3. Remove old processed_by_user_id CharField ─────────────
        # Column may already have been dropped in the live DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="indent",
                    name="processed_by_user_id",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "indents" DROP COLUMN IF EXISTS "processed_by_user_id";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        # ── 4. Add processed_by FK (db_column='processed_by_id') ─────
        # Column may already exist in the live DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="indent",
                    name="processed_by",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="processed_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'indents' AND column_name = 'processed_by_id'
                        ) THEN
                            ALTER TABLE "indents"
                                ADD COLUMN "processed_by_id" integer NULL
                                REFERENCES "auth_user" ("id")
                                DEFERRABLE INITIALLY DEFERRED;
                            CREATE INDEX "indents_processed_by_id_idx"
                                ON "indents" ("processed_by_id");
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        # ── 5. StockSnapshot id: AutoField → BigAutoField ────────────
        # Column may already be bigint in the live DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="stocksnapshot",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    DECLARE
                        col_type text;
                    BEGIN
                        SELECT data_type INTO col_type
                        FROM information_schema.columns
                        WHERE table_name = 'stock_snapshots' AND column_name = 'id';
                        IF col_type = 'integer' THEN
                            ALTER TABLE "stock_snapshots" ALTER COLUMN "id" TYPE bigint;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
