# Generated by Django 5.2.5 on 2026-03-19 18:43
#
# po_number and line_total columns already exist in the live DB.
# This migration is state-only so Django's ORM knows about the fields
# without attempting to re-create the columns.

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("inventory", "0024_fix_pk_sequences"),
    ]

    operations = [
        # po_number already exists in purchase_orders table
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="purchaseorder",
                    name="po_number",
                    field=models.TextField(default=""),
                ),
            ],
            database_operations=[],  # Column already exists
        ),
        # line_total already exists in purchase_order_items table
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="purchaseorderitem",
                    name="line_total",
                    field=models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
            ],
            database_operations=[],  # Column already exists
        ),
        # Recipe type choices -- state-only (no DDL for choices on CharField)
        migrations.AlterField(
            model_name="recipe",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select type..."),
                    ("MAIN", "Main Course"),
                    ("APPETIZER", "Appetizer / Starter"),
                    ("DESSERT", "Dessert"),
                    ("BEVERAGE", "Beverage"),
                    ("PREP", "Prep / Base Recipe"),
                    ("SAUCE", "Sauce / Dressing"),
                    ("SIDE", "Side Dish"),
                    ("BATCH", "Batch Production"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
