# Generated by Django 5.2.5 on 2026-03-19
#
# Simplifies PurchaseOrder status from 5 choices to 3:
#   DRAFT  → unchanged
#   ORDERED + PARTIAL  → SENT ("Sent to Supplier")
#   COMPLETE → RECEIVED ("Received")
#   CANCELLED → unchanged
#
# No existing POs in the database, so no data migration is required.
# Django stores choices as plain VARCHAR — no DDL is needed for choice changes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_indent_source_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent to Supplier"),
                    ("RECEIVED", "Received"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
