# Generated by Django 5.2.5 on 2026-03-28 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_siteconfig_quantity_decimal_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksnapshot',
            options={'managed': True, 'ordering': ['snapshot_date']},
        ),
        migrations.AlterUniqueTogether(
            name='recipecomponent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='indent',
            name='processed_by_user_id',
        ),
        migrations.AddField(
            model_name='indent',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
