# Generated by Django 5.2.5 on 2026-03-28 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_siteconfig_quantity_decimal_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksnapshot',
            options={'managed': True, 'ordering': ['snapshot_date']},
        ),
        # RecipeComponent.unique_together was removed in Django state. Production
        # PostgreSQL often has no matching UNIQUE constraint (schema drift / prior
        # manual DDL), so a plain AlterUniqueTogether raises ValueError when Django
        # tries to drop a non-existent constraint. State-only update matches 0029.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="recipecomponent",
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='indent',
            name='processed_by_user_id',
        ),
        migrations.AddField(
            model_name='indent',
            name='processed_by',
            field=models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
