# Generated by Django 5.2.5 on 2026-05-21 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_supabase_schema_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSMenuItemMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_item_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_menu_item_mappings',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='gross_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='net_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='outlet',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='pos_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('POS_CSV', 'POS CSV Import')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='source_row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['sale_date'], name='idx_sale_txn_date'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['source'], name='idx_sale_txn_source'),
        ),
        migrations.AddField(
            model_name='posmenuitemmapping',
            name='recipe',
            field=models.ForeignKey(blank=True, db_column='recipe_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_mappings', to='inventory.recipe'),
        ),
        migrations.AddIndex(
            model_name='posmenuitemmapping',
            index=models.Index(fields=['is_active'], name='idx_pos_map_active'),
        ),
    ]
