# Generated by Django 5.2.5 on 2026-05-21

from django.db import migrations, models


def normalize_wastage_reason_codes(apps, schema_editor):
    StockTransaction = apps.get_model("inventory", "StockTransaction")
    mappings = {
        "SPOILAGE": "SPOILED",
        "EXPIRY": "EXPIRED",
        "OVERCOOKING": "OVER_PREPPED",
    }
    for old_value, new_value in mappings.items():
        StockTransaction.objects.filter(reason_category=old_value).update(
            reason_category=new_value
        )
    StockTransaction.objects.filter(
        transaction_type="WASTAGE",
    ).exclude(
        reason_category__in={
            "SPOILED",
            "EXPIRED",
            "OVER_PREPPED",
            "BURNT",
            "RETURNED",
            "BREAKAGE",
            "STAFF_MEAL",
            "OTHER",
            None,
            "",
        }
    ).update(reason_category="OTHER")


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0044_posmenuitemmapping_saletransaction_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="wastage_photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="wastage_photos/",
            ),
        ),
        migrations.RunPython(
            normalize_wastage_reason_codes,
            migrations.RunPython.noop,
        ),
    ]
