# Generated by Django 5.2.5 on 2025-08-19 10:54

import django.db.models.deletion
from django.db import migrations, models

import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grnitem",
            name="unit_price_at_receipt",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="SaleTransaction",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", inventory.models.CoerceFloatField(blank=True, null=True)),
                ("user_id", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        db_column="recipe_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "sales_transactions",
            },
        ),
    ]
