# Generated by Django 5.2.5 on 2025-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_indent_department_alter_indent_mrn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grnitem",
            name="item_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
