# Generated by Django 5.2.5 on 2025-08-22 21:23

import django.db.models.deletion
from django.db import migrations, models


def forward_migrate(apps, schema_editor):
    Item = apps.get_model("inventory", "Item")
    Category = apps.get_model("inventory", "Category")
    for item in Item.objects.all():
        if getattr(item, "category", None):
            cat = Category.objects.filter(name=item.category).first()
            if cat:
                item.category_fk_id = cat.id
        if getattr(item, "sub_category", None):
            sub = Category.objects.filter(name=item.sub_category).first()
            if sub:
                item.sub_category_fk_id = sub.id
        item.save(update_fields=["category_fk", "sub_category_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="items",
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sub_category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sub_items",
                to="inventory.category",
            ),
        ),
        migrations.RunPython(
            code=forward_migrate,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="sub_category",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category_fk",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="sub_category_fk",
            new_name="sub_category",
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="items",
                to="inventory.category",
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sub_items",
                to="inventory.category",
                blank=True,
                null=True,
            ),
        ),
    ]
