# Generated by Django 5.2.5 on 2025-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_remove_category_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category_id",
            field=models.IntegerField(blank=True, db_column="category", null=True),
        ),
    ]
