# Generated by Django 5.2.5 on 2025-08-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_auto_20250825_1234"),
    ]

    operations = []
