# Generated by Django 5.2.5 on 2025-08-26 20:55

from django.db import migrations


class Migration(migrations.Migration):
    """
    Enable Django management for all inventory models.
    This migration only changes the managed=True flag in model meta options
    without altering the actual database schema, which already exists in Supabase.
    """

    dependencies = [
        ("inventory", "0018_indent_managed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsreceivednote",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="grnitem",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="indent",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="indentitem",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="purchaseorderitem",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="recipecomponent",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="saletransaction",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="stocktransaction",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"managed": True},
        ),
    ]
